---
apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  annotations:
    # agentBareMetal-agentSelector/autoSelect: "false"
    agentclusterinstalls.extensions.hive.openshift.io/location: fr-lab
  labels:
    cluster.open-cluster-management.io/clusterset: 'default'
    hive.openshift.io/cluster-platform: agent-baremetal
  name: 'sno-blueprint'
  namespace: 'sno-blueprint'
spec:
  baseDomain: clustership.com
  clusterInstallRef:
    group: extensions.hive.openshift.io
    kind: AgentClusterInstall
    name: sno-blueprint
    version: v1beta1
  clusterName: sno-blueprint
  controlPlaneConfig:
    servingCertificates: {}
  installed: false
  platform:
    agentBareMetal: 
      agentSelector: {}
  pullSecretRef:
    name: pullsecret-cluster-sno-blueprint
