---
apiVersion: v1
data:
  password: cm91Z2VmZXVZWQ==
  username: cm9vdA==
kind: Secret
metadata:
  creationTimestamp: null
  name: bmc-bm-compact-blueprint
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  annotations:
    bmac.agent-install.openshift.io/hostname: bm-compact-blueprint-master-1
    bmac.agent-install.openshift.io/role: master
    # inspect.metal3.io: disabled
  labels:
    infraenvs.agent-install.openshift.io: bm-compact-blueprint
  name: bm-compact-blueprint-master-1
  namespace: bm-compact-blueprint
spec:
  automatedCleaningMode: disabled
  bmc:
    address: idrac-virtualmedia://172.18.10.101/redfish/v1/Systems/System.Embedded.1
    credentialsName: bmc-bm-compact-blueprint
    disableCertificateVerification: true
  bootMACAddress: "24:6E:96:6C:2A:34"
  online: true
---
apiVersion: v1
data:
  password: cm91Z2VmZXVZWQ==
  username: cm9vdA==
kind: Secret
metadata:
  creationTimestamp: null
  name: bmc-bm-compact-02
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  annotations:
    bmac.agent-install.openshift.io/hostname: bm-compact-blueprint-master-2
    bmac.agent-install.openshift.io/role: master
    # inspect.metal3.io: disabled
  labels:
    infraenvs.agent-install.openshift.io: bm-compact-blueprint
  name: bm-compact-blueprint-master-2
  namespace: bm-compact-blueprint
spec:
  automatedCleaningMode: disabled
  bmc:
    address: idrac-virtualmedia://172.18.10.104/redfish/v1/Systems/System.Embedded.1
    credentialsName: bmc-bm-compact-02
    disableCertificateVerification: true
  bootMACAddress: "24:6E:96:8E:54:98"
  # bootMACAddress: "24:6E:96:8E:54:99"
  online: true
---
apiVersion: v1
data:
  password: cm91Z2VmZXVZWQ==
  username: cm9vdA==
kind: Secret
metadata:
  creationTimestamp: null
  name: bmc-bm-compact-03
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  annotations:
    bmac.agent-install.openshift.io/hostname: bm-compact-blueprint-master-3
    bmac.agent-install.openshift.io/role: master
    # inspect.metal3.io: disabled
  labels:
    infraenvs.agent-install.openshift.io: bm-compact-blueprint
  name: bm-compact-blueprint-master-3
  namespace: bm-compact-blueprint
spec:
  automatedCleaningMode: disabled
  bmc:
    address: idrac-virtualmedia://172.18.10.105/redfish/v1/Systems/System.Embedded.1
    credentialsName: bmc-bm-compact-03
    disableCertificateVerification: true
  bootMACAddress: "24:6E:96:8E:4E:8C"
  # rootDeviceHints:
  #   hctl: 6:0:0:0
  online: true
