---
apiVersion: extensions.hive.openshift.io/v1beta1
kind: AgentClusterInstall
metadata:
  name: bm-compact-blueprint
  namespace: bm-compact-blueprint
  labels:
    agentclusterinstalls.extensions.hive.openshift.io/location: fr-lab
    cluster-type: compact
spec:
  clusterDeploymentRef:
    name: 'bm-compact-blueprint'
  # holdInstallation: true
  provisionRequirements:
    workerAgents: 0
    controlPlaneAgents: 3
  imageSetRef:
    name: img4.12.16-x86-64-appsub
    # name: img4.10.37-x86-64-appsub
    # name: img4.11.28-x86-64-appsub
  apiVIP: 172.16.1.210
  ingressVIP: 172.16.1.211
  networking:
    networkType: OVNKubernetes
    clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
    machineNetwork:
      - cidr: 172.16.1.0/24
    serviceNetwork:
      - 172.30.0.0/16
  sshPublicKey: >-
    ssh-rsa AAAA<CHANGEME>
