---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  labels:
    cloud: hybrid
    name: 'bm-compact-blueprint'
    cluster.open-cluster-management.io/clusterset: 'open5gs'
    clusterType: 'compact'
  name: 'bm-compact-blueprint'
spec:
  hubAcceptsClient: true
