---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: 'bm-compact-blueprint'
  namespace: 'bm-compact-blueprint'
spec:
  clusterName: 'bm-compact-blueprint'
  clusterNamespace: 'bm-compact-blueprint'
  clusterLabels:
    cloud: hybrid
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true
