kind: Service
apiVersion: v1
metadata:
  annotations:
    metallb.universe.tf/address-pool: ip-addresspool-hypershift-router
  name: metallb-hypershift-ingress
  namespace: openshift-ingress
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  selector:
    hypershift.openshift.io/hosted-control-plane: clusters-bm-hypershift-01
    ingresscontroller.operator.openshift.io/deployment-ingresscontroller: hypershift-router-shard
  type: LoadBalancer
