apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- 01-ip-address-pool-router-shard.yaml
- 02-l2-adv-router-shard.yaml
- 03-hypershift-router-shard.yaml
# - 03-ingress-lb-service.yaml
